---
# tasks file for myfirewall
- name: Ensure firewalld is installed
  yum:
    name: firewalld
    state: latest

- name: Ensure firewalld is installed and enabled
  service:
    name: firewalld
    state: started
    enabled: true

- name: Ensure firewalld services are enabled.
  firewalld:
    state: enabled
    immediate: true
    permanent: true
    service: "{{ item }}"
  loop: "{{ firewall_services }}"
