---
- name: using the copy module
  hosts: all
  remote_user: root

  tasks:
    - name: copy files to the managed hosts and set attribute
      copy:
        src: files/users.txt
        dest: /home/devops/users.txt
        owner: devops
        group: devops
        mode: u+rw, g-wx, o-rwx
        setype: samba_share_t


