---
- name: use the fetch module to retrieve secure log files
  hosts: all
  remote_user: root
  tasks:
    - name: Fetch the /var/log/secure log file from the managed hosts.
      fetch:
        src: /var/log/secure
        dest: secure-backups
        flat: no
